name: Deploy Log Service to AWS Lambda

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch: # Enable manual triggering

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed to checkout the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.0.0"

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: terraform
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Post-Deployment Tests
        run: |
          echo "Running post-deployment tests..."
          API_ENDPOINT=$(terraform output -raw api_endpoint)
          echo "API Endpoint: $API_ENDPOINT"
          curl -X POST -H "Content-Type: application/json" -d '{"id": "test-id", "timestamp": '$(date +%s)', "severity": "info", "message": "Test log entry"}' $API_ENDPOINT/addlog
          curl -X GET $API_ENDPOINT/getlogs
          echo "Post-deployment tests passed."
